version: "2"
services:
  namenode-primary-data:
    image: actionml/hadoop
    command: format-namenode
    network_mode: none

  datanode-1-data:
    image: actionml/hadoop
    command: /bin/true
    network_mode: none

  datanode-2-data:
    image: actionml/hadoop
    command: /bin/true
    network_mode: none

  bootstrap-hdfs:
    image: actionml/hadoop
    command: bootstrap-hdfs
    depends_on:
      - datanode-1
      - namenode-primary
    environment:
      - WAITFORSTART=20
      - HADOOP_NAMENODE_ADDRESS=namenode-primary

  namenode-primary:
    image: actionml/hadoop
    command: hdfs namenode
    environment:
      - WAITFORSTART=5
    volumes_from:
      - namenode-primary-data
    ports:
      - 50070:50070

  datanode-1:
    image: actionml/hadoop
    command: hdfs datanode
    depends_on:
      - namenode-primary
    environment:
      - HADOOP_NAMENODE_ADDRESS=namenode-primary
      - WAITFORSTART=15
    volumes_from:
      - datanode-1-data

  datanode-2:
    image: actionml/hadoop
    command: hdfs datanode
    depends_on:
      - namenode-primary
    environment:
      - HADOOP_NAMENODE_ADDRESS=namenode-primary
      - WAITFORSTART=15
    volumes_from:
      - datanode-2-data

networks:
  default:
    external:
      name: actionml
