version: 2
jobs:
  build:
    docker:
    - image: stackfeed/circle-shell
    environment:
      PROJECT: docker-hadoop
      NAMESPACE: actionml
      PUSH_NAMESPACES: actionml
      CONTINUOUS_INTEGRATION: "yes"
    steps:
    - checkout

  publish:
    docker:
    - image: docker:stable

    steps:
    - checkout
    - setup_remote_docker
    - run:
        name: Docker login
        command: |
          echo "DOCKER_ENV_VAR - ${DOCKER_PASSWORD} - ${DOCKER_USERNAME}"
          echo -n ${DOCKER_PASSWORD} | docker login -u ${DOCKER_USERNAME} --password-stdin
    - run:
        name: Build docker-hadoop image
        command: |
          SHORT_GIT_HASH=$(echo $CIRCLE_SHA1 | cut -c -7)
          DATE_BUILD=$(date +'%Y-%m-%d')

          case "${CIRCLE_BRANCH}" in
            "master")
              docker image build -f Dockerfile \
              --build-arg GIT_HASH=$SHORT_GIT_HASH \
              --build-arg DATE_BUILD=$DATE_BUILD \
              --build-arg BRANCH=${CIRCLE_BRANCH} -t actionml/hadoop:latest ./
            ;;
            "develop")
              docker image build -f Dockerfile \
              --build-arg GIT_HASH=$SHORT_GIT_HASH \
              --build-arg DATE_BUILD=$DATE_BUILD \
              --build-arg BRANCH=${CIRCLE_BRANCH} -t actionml/hadoop:${CIRCLE_BRANCH} ./
            ;;
            "devops")
              docker image build -f Dockerfile \
              --build-arg GIT_HASH=$SHORT_GIT_HASH \
              --build-arg DATE_BUILD=$DATE_BUILD \
              --build-arg BRANCH=${CIRCLE_BRANCH} -t actionml/hadoop:${CIRCLE_BRANCH} ./
            ;;
            "ci")
              docker image build -f Dockerfile \
              --build-arg GIT_HASH=$SHORT_GIT_HASH \
              --build-arg DATE_BUILD=$DATE_BUILD \
              --build-arg BRANCH=${CIRCLE_BRANCH} -t actionml/hadoop:${CIRCLE_BRANCH} ./
            ;;
            *)
            ;;
          esac
    # - run:
    #     name: Publish docker image
    #     command: |
    #       SHORT_GIT_HASH=$(echo $CIRCLE_SHA1 | cut -c -7)
    #       DATE_BUILD=$(date +'%Y-%m-%d')
          
    #       case "${CIRCLE_BRANCH}" in
    #         "master")
    #           docker image push actionml/hadoop:latest
    #         ;;
    #         "develop")
    #           docker image push actionml/hadoop:${CIRCLE_BRANCH}
              
    #           docker tag actionml/hadoop:${CIRCLE_BRANCH} actionml/hadoop:${CIRCLE_BRANCH}-${SHORT_GIT_HASH}
    #           docker image push actionml/hadoop:${CIRCLE_BRANCH}-${SHORT_GIT_HASH}
              
    #           docker tag actionml/hadoop:${CIRCLE_BRANCH} actionml/hadoop:${CIRCLE_BRANCH}-${DATE_BUILD}
    #           docker image push actionml/hadoop:${CIRCLE_BRANCH}-${DATE_BUILD}
    #         ;;
    #         "devops")
    #           docker image push actionml/hadoop:${CIRCLE_BRANCH}
              
    #           docker tag actionml/hadoop:${CIRCLE_BRANCH} actionml/hadoop:${CIRCLE_BRANCH}-${SHORT_GIT_HASH}
    #           docker image push actionml/hadoop:${CIRCLE_BRANCH}-${SHORT_GIT_HASH}
              
    #           docker tag actionml/hadoop:${CIRCLE_BRANCH} actionml/hadoop:${CIRCLE_BRANCH}-${DATE_BUILD}
    #           docker image push actionml/hadoop:${CIRCLE_BRANCH}-${DATE_BUILD}
    #         ;;
    #         "ci")
    #           docker image push actionml/hadoop:${CIRCLE_BRANCH}
              
    #           docker tag actionml/hadoop:${CIRCLE_BRANCH} actionml/hadoop:${CIRCLE_BRANCH}-${SHORT_GIT_HASH}
    #           docker image push actionml/hadoop:${CIRCLE_BRANCH}-${SHORT_GIT_HASH}
              
    #           docker tag actionml/hadoop:${CIRCLE_BRANCH} actionml/hadoop:${CIRCLE_BRANCH}-${DATE_BUILD}
    #           docker image push actionml/hadoop:${CIRCLE_BRANCH}-${DATE_BUILD}
    #         ;;
    #         *)
    #         ;;
    #       esac
  test:
    docker:
    - image: alpine
    steps:
    - run: echo "unit or other tests"

workflows:
  version: 2
  default:
    jobs:
    - build
    - test
    - publish:
        requires:
        - build
        - test
